In [1]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler
import numpy as np

# =============================================================================
# Some data: 6 samples, 2 features
# =============================================================================
X = np.array([[0, 1, 2, 3, 4, 5], [0, 2, 4, 6, 8, 10]]).T
Z = np.array([[0, 1, 2, 3, 4, 5], [0, 2, 4, 6, 8, 999]]).T

print("X:\n", X)
print("Z:\n", Z)


X:
 [[ 0  0]
 [ 1  2]
 [ 2  4]
 [ 3  6]
 [ 4  8]
 [ 5 10]]
Z:
 [[  0   0]
 [  1   2]
 [  2   4]
 [  3   6]
 [  4   8]
 [  5 999]]


In [2]:
# =============================================================================
# Normalising using the MinMaxScaler (put all values in range [min,max]; default [0,1]; sensitive to outliers)
# =============================================================================
mms = MinMaxScaler()
X_mms = mms.fit_transform(X) # fit and transform in one step, equivalent to mms.fit(X) and then mms.transform(X)
Z_mms = mms.fit_transform(Z)

print("X_mms:\n", X_mms)
print("Z_mms:\n", Z_mms)

# print min, max, mean and std for X
print(f"X: min={np.min(X_mms, axis=0)}, max={np.max(X_mms, axis=0)}, mean={np.mean(X_mms, axis=0)}, std={np.std(X_mms, axis=0)}")
# print min, max, mean and std for Z
print(f"Z: min={np.min(Z_mms, axis=0)}, max={np.max(Z_mms, axis=0)}, mean={np.mean(Z_mms, axis=0)}, std={np.std(Z_mms, axis=0)}")

X_mms:
 [[0.  0. ]
 [0.2 0.2]
 [0.4 0.4]
 [0.6 0.6]
 [0.8 0.8]
 [1.  1. ]]
Z_mms:
 [[0.         0.        ]
 [0.2        0.002002  ]
 [0.4        0.004004  ]
 [0.6        0.00600601]
 [0.8        0.00800801]
 [1.         1.        ]]
X: min=[0. 0.], max=[1. 1.], mean=[0.5 0.5], std=[0.34156503 0.34156503]
Z: min=[0. 0.], max=[1. 1.], mean=[0.5        0.17000334], std=[0.34156503 0.37119479]


In [3]:
# =============================================================================
# Standardising unsing the StandardScaler
# =============================================================================
stdsc = StandardScaler()
X_std = stdsc.fit_transform(X)
Z_std = stdsc.fit_transform(Z)

print("X_std:\n", X_std)
print("Z_std:\n", Z_std)

# print min, max, mean and std for X
print(f"X: min={np.min(X_std, axis=0)}, max={np.max(X_std, axis=0)}, mean={np.mean(X_std, axis=0)}, std={np.std(X_std, axis=0)}")
# print min, max, mean and std for Z
print(f"Z: min={np.min(Z_std, axis=0)}, max={np.max(Z_std, axis=0)}, mean={np.mean(Z_std, axis=0)}, std={np.std(Z_std, axis=0)}")

X_std:
 [[-1.46385011 -1.46385011]
 [-0.87831007 -0.87831007]
 [-0.29277002 -0.29277002]
 [ 0.29277002  0.29277002]
 [ 0.87831007  0.87831007]
 [ 1.46385011  1.46385011]]
Z_std:
 [[-1.46385011 -0.45798955]
 [-0.87831007 -0.45259615]
 [-0.29277002 -0.44720275]
 [ 0.29277002 -0.44180935]
 [ 0.87831007 -0.43641595]
 [ 1.46385011  2.23601377]]
X: min=[-1.46385011 -1.46385011], max=[1.46385011 1.46385011], mean=[-3.70074342e-17 -3.70074342e-17], std=[1. 1.]
Z: min=[-1.46385011 -0.45798955], max=[1.46385011 2.23601377], mean=[-3.70074342e-17  0.00000000e+00], std=[1. 1.]
